### ISSUE TITLE
Documentation issue cohesity_source module

### ISSUE THREAD

**Issue by kortstie** [cohesity/cohesity-ansible-role#11]
Hi Cohesity,
in the examples section of the sorce module:

https://cohesity.github.io/cohesity-ansible-role/#/modules/cohesity_source

the parameter "server" is mentioned several times:

```
- cohesity_source:
    server: cohesity.lab
    username: admin
    password: password
    endpoint: mylinux.host.lab
   state: present
```
- the parameter server is rejected, the right one should be
    cluster: xxx
- also the parameter 
   environment:
is missing, but it is a required parameter.

Thanks, Frank
