### ISSUE TITLE
endpoint sets itself to null in cohesity_job module

### ISSUE THREAD

**Issue by mgaruccio** [cohesity/cohesity-ansible-role#31]
I am attempting to create backup jobs using the cohesity_job module to create new backup jobs and getting the error `"Unexpected error caused while managing the Cohesity Module."`.  with an error details message telling me to specify one or more sources to back up, even though endpoints are included in my playbook.

running with the `-vvv` switch I see that the `endpoint` is somehow being set to `null` when the module is invoked, even though it is a simple string in my playbook.  I did try adding additional items to the list, and they do appear, but all of the values for the `endpoint` key are switched to `null`. 

**errors**
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "error_class": "bytes",
    "error_details": "b'{\"errorCode\":\"KValidationError\",\"message\":\"Please specify one or more sources to backup.\"}\\n'",
    "invocation": {
        "module_args": {
            "cancel_active": false,
            "cluster": "10.181.224.10",
            "delete_backups": false,
            "description": null,
            "environment": "VMware",
            "name": "test",
            "ondemand_run_type": "Regular",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "protection_policy": "Gold",
            "protection_sources": [
                {
                    "endpoint": null
                }
            ],
            "start_time": null,
            "state": "present",
            "storage_domain": "DefaultStorageDomain",
            "time_zone": "America/Los_Angeles",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "validate_certs": false
        }
    },
    "msg": "Unexpected error caused while managing the Cohesity Module."
}
```

playbook
```
---
- name: Create backup jobs
  hosts: localhost
  gather_facts: no
  become: false

  tasks:
  - name: create new protection job
    cohesity_job:
      cluster: _cluster-vip_
      username: _username_
      password: _password_
      state: present
      name: test
      environment: VMware
      protection_sources:
      - endpoint: vcsa01.skunkworkx.cloud
      protection_policy: Gold
      storage_domain: DefaultStorageDomain
```

**Comment by anvesh-cohesity** [comment]
In the playbook above please change protection_sources to sources

**Comment by mgaruccio** [comment]
Changing that variable results in an error about using an unsupported parameter since the module doesn't have a `sources` argument.

**Comment by anvesh-cohesity** [comment]
Can I see the playbook and the error logs. Pls run the playbook with -vvv switch

**Comment by mgaruccio** [comment]
playbook - 

```
---
- name: Create backup jobs
  hosts: localhost
  gather_facts: no
  become: false

  tasks:
  - name: create new protection job
    cohesity_job:
      cluster: _cluster-vip_
      username: _username_
      password: _password_
      state: present
      name: test
      environment: VMware
      protection_sources:
      - endpoint: vcsa01.skunkworkx.cloud
      protection_policy: Gold
      storage_domain: DefaultStorageDomain
```

full logs - 
```
ansible-playbook backup-test.yml -vvv                                                         
ansible-playbook 2.8.0
  config file = None
  configured module search path = ['/Users/mike.garuccio/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mike.garuccio/.local/share/virtualenvs/cohesity-backup-restore-Lt0zhOPp/lib/python3.7/site-packages/ansible
  executable location = /Users/mike.garuccio/.local/share/virtualenvs/cohesity-backup-restore-Lt0zhOPp/bin/ansible-playbook
  python version = 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
No config file found; using defaults
host_list declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAYBOOK: backup-test.yml *****************************************************************************************************************************************************************************************************************
1 plays in backup-test.yml

PLAY [Create backup jobs] *****************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [create new protection job] **********************************************************************************************************************************************************************************************************
task path: /Users/mike.garuccio/code/cohesity-backup-restore/backup-test.yml:16
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: mike.garuccio
<127.0.0.1> EXEC /bin/sh -c 'echo ~mike.garuccio && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/mike.garuccio/.ansible/tmp/ansible-tmp-1564706984.7987058-194040580788991 `" && echo ansible-tmp-1564706984.7987058-194040580788991="` echo /Users/mike.garuccio/.ansible/tmp/ansible-tmp-1564706984.7987058-194040580788991 `" ) && sleep 0'
Using module file /Users/mike.garuccio/code/cohesity-backup-restore/library/cohesity_job.py
<127.0.0.1> PUT /Users/mike.garuccio/.ansible/tmp/ansible-local-3342fwqxevmc/tmpthma2jdf TO /Users/mike.garuccio/.ansible/tmp/ansible-tmp-1564706984.7987058-194040580788991/AnsiballZ_cohesity_job.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/mike.garuccio/.ansible/tmp/ansible-tmp-1564706984.7987058-194040580788991/ /Users/mike.garuccio/.ansible/tmp/ansible-tmp-1564706984.7987058-194040580788991/AnsiballZ_cohesity_job.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/Users/mike.garuccio/.local/share/virtualenvs/cohesity-backup-restore-Lt0zhOPp/bin/python3.7 /Users/mike.garuccio/.ansible/tmp/ansible-tmp-1564706984.7987058-194040580788991/AnsiballZ_cohesity_job.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/mike.garuccio/.ansible/tmp/ansible-tmp-1564706984.7987058-194040580788991/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/var/folders/2c/c2l4yx8s1pqfgq1vtrtbwzdh0000gp/T/ansible_cohesity_job_payload_e8hnc3x6/__main__.py", line 370, in register_job
    validate_certs=validate_certs)
  File "/var/folders/2c/c2l4yx8s1pqfgq1vtrtbwzdh0000gp/T/ansible_cohesity_job_payload_e8hnc3x6/ansible_cohesity_job_payload.zip/ansible/module_utils/urls.py", line 1251, in open_url
    use_gssapi=use_gssapi, unix_socket=unix_socket)
  File "/var/folders/2c/c2l4yx8s1pqfgq1vtrtbwzdh0000gp/T/ansible_cohesity_job_payload_e8hnc3x6/ansible_cohesity_job_payload.zip/ansible/module_utils/urls.py", line 1157, in open
    r = urllib_request.urlopen(*urlopen_args)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "error_class": "bytes",
    "error_details": "b'{\"errorCode\":\"KValidationError\",\"message\":\"Please specify one or more sources to backup.\"}\\n'",
    "invocation": {
        "module_args": {
            "cancel_active": false,
            "cluster": "10.181.224.10",
            "delete_backups": false,
            "description": null,
            "environment": "VMware",
            "name": "test",
            "ondemand_run_type": "Regular",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "protection_policy": "Gold",
            "protection_sources": [
                {
                    "endpoint": null
                }
            ],
            "start_time": null,
            "state": "present",
            "storage_domain": "DefaultStorageDomain",
            "time_zone": "America/Los_Angeles",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "validate_certs": false
        }
    },
    "msg": "Unexpected error caused while managing the Cohesity Module."
}

PLAY RECAP ********************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by anvesh-cohesity** [comment]
The job module reads the variables from tasks https://cohesity.github.io/cohesity-ansible-role/#/tasks/job, https://github.com/cohesity/cohesity-ansible-role/blob/master/tasks/job.yml where we read **sources** from playbook. 
Please follow this documentation to write the playbooks related to jobs https://cohesity.github.io/cohesity-ansible-role/#/examples/demos/jobs. 
For more playbook examples, pls check https://github.com/cohesity/cohesity-ansible-role/tree/master/examples/demos. 
Pls use the playbook below to create a protection job for VMware environment
```yaml---
  - hosts: local
    gather_facts: no
    roles:
      - cohesity.cohesity_ansible_role
    tasks:
      - name: Protection job
        include_role:
          name: cohesity.cohesity_ansible_role
          tasks_from: job
        vars:
          cohesity_server: 11.22.100.21
          cohesity_admin: "{{ username }}"
          cohesity_password: "{{ password }}"
          cohesity_validate_certs: False
          cohesity_protection:
              state: present
              job_name: protect_vcenter
              storage_domain: "DefaultStorageDomain"
              policy: "test policy"
              sources:
                - endpoint: "12.11.230.14"
              environment: "VMware"

**Comment by mgaruccio** [comment]
That would have me using the job role rather than the job module, which is fine but adds additional complexity to the playbook.  is there a reason when I call the module directly the endpoint becomes `null` but when using the role it seems to come through?

**Comment by mgaruccio** [comment]
Actually I just tested again and I'm seeing the same issue.  Oddly enough if I use an existing backup job name the endpoint *does* get populated in the module invocation, which is what I saw that appeared to be working, but when providing a name of a job that does not currently exist I get the same error as before and the module invocation shows the endpoint as null.  examples below.

**with job name that already exists**  - 
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "id": 57482,
    "invocation": {
        "module_args": {
            "cancel_active": false,
            "cluster": "10.181.224.10",
            "delete_backups": false,
            "description": null,
            "environment": "VMware",
            "name": "test-job",
            "ondemand_run_type": "Regular",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "protection_policy": "Bronze",
            "protection_sources": [
                {
                    "endpoint": "vcsa01.skunkworx.cloud"
                }
            ],
            "start_time": null,
            "state": "present",
            "storage_domain": "DefaultStorageDomain",
            "time_zone": "America/Los_Angeles",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "validate_certs": false
        }
    },
    "msg": "The protection job already exists",
    "name": "test-job"
}
```

**and with job that doesn't currently exist** -
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "error_class": "bytes",
    "error_details": "b'{\"errorCode\":\"KValidationError\",\"message\":\"Please specify one or more sources to backup.\"}\\n'",
    "invocation": {
        "module_args": {
            "cancel_active": false,
            "cluster": "10.181.224.10",
            "delete_backups": false,
            "description": null,
            "environment": "VMware",
            "name": "test-job2",
            "ondemand_run_type": "Regular",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "protection_policy": "Bronze",
            "protection_sources": [
                {
                    "endpoint": null
                }
            ],
            "start_time": null,
            "state": "present",
            "storage_domain": "DefaultStorageDomain",
            "time_zone": "America/Los_Angeles",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "validate_certs": false
        }
    },
    "msg": "Unexpected error caused while managing the Cohesity Module."
}
```

The playbook I'm running here is copied below with username/password blanked, the only difference between the two runs above is the job name.

```
---
- hosts: localhost
  vars:
    var_cohesity_server: 10.181.224.10
    var_cohesity_admin:
    var_cohesity_password:
    var_validate_certs: False
  gather_facts: no
  roles:
  - cohesity-ansible-role
  tasks:
  - name: create vmware prot job
    include_role:
      name: cohesity-ansible-role
      tasks_from: job
    vars:
      cohesity_server: "{{ var_cohesity_server }}"
      cohesity_admin: "{{ var_cohesity_admin }}"
      cohesity_password: "{{ var_cohesity_password }}"
      cohesity_validate_certs: "{{ var_validate_certs }}"
      cohesity_protection:
        state: present
        job_name: 'test-job2'
        sources:
        - endpoint: 'vcsa01.skunkworx.cloud'
        environment: VMware
```
