### ISSUE TITLE
How to add a server to existing protection job without specifying all servers

### ISSUE THREAD

**Issue by jtrutwin** [cohesity/cohesity-ansible-role#56]
In my scenario I have a protection job named TEST_JOB_JT that has 5 vm's protected.  I would like to use this ansible module to a 6th server named "my-new-server" to the job so I tried this:

```yaml
    - name: Add server to protection job
      cohesity_job:
        cluster: "{{ cohesity_cluster }}"
        username: "{{ cohesity_api_user }}"
        password: "{{ cohesity_api_pass }}"
        validate_certs: false
        state: present
        name: TEST_JOB_JT
        environment: VMware
        include:
          - my-new-server
      register: cohesity_protection
```

This unfortunately changes the job to only have "my-new-server" in the job and the original 5 servers are removed.  Is this possible or do I need to list all servers in the job under the "include:" section?  If so, how do you get the server names in a job?  In the cohesity_facts module for jobs it lists them as "sourceIds" with numeric id numbers instead of vm names.

Thanks,
Josh

**Comment by naveena-maplelabs** [comment]
@jtrutwin you can set **append_to_existing** to True, which will add new sources to the existing sources.
```
    - name: Add server to protection job
      cohesity_job:
        cluster: "{{ cohesity_cluster }}"
        username: "{{ cohesity_api_user }}"
        password: "{{ cohesity_api_pass }}"
        validate_certs: false
        state: present
        name: TEST_JOB_JT
        environment: VMware
        append_to_existing: True
        include:
          - my-new-server
      register: cohesity_protection
```
